### ISSUE TITLE
TasmotaSerial-2.4.0 does not work with core 2.3.0

### ISSUE THREAD

**Issue by qingz2004** [arendst/Sonoff-Tasmota#6391]
Here is the error message during compilation:

> lib/TasmotaSerial-2.4.0/src/TasmotaSerial.cpp: In member function 'void TasmotaSerial::rxRead()':
> lib/TasmotaSerial-2.4.0/src/TasmotaSerial.cpp:280:7: error: 'TM_SERIAL_WAIT_RCV_LOOP' was not declared in this scope
>        TM_SERIAL_WAIT_RCV_LOOP;    // wait for stop bit
>        ^
> *** [.pioenvs/sonoff/lib879/TasmotaSerial-2.4.0/TasmotaSerial.cpp.o] Error 1

Adding a define line between line 220 and 221 in file TasmotaSerial.cpp fixed it.
#define TM_SERIAL_WAIT_RCV_LOOP { while (ESP.getCycleCount() < (wait + start)); }

**Comment by s-hadinger** [comment]
I'll look at it tomorrow if Theo doesn't fix it before me :)
